services:
  db:
    image: postgres:18-alpine
    container_name: skillup-campus-db
    environment:
      POSTGRES_USER: skillup-campus
      POSTGRES_PASSWORD: skillup-campus
      POSTGRES_DB: skillup-campus
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skillup-campus -d skillup-campus"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
